apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HPALimitReplicas
metadata:
  name: hpalimitreplicasconstraint
spec:
  parameters:
    maxReplicas: 5
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["HorizontalPodAutoscaler"]
#    namespaces: ["*"]
#    alternatively, scope by a selector
#    namespaceSelector:
#      matchExpressions:
#        - key: istio-injection
#          operator: In
#          values: ["enabled"]
