apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHpaLimit
metadata:
  name: hpa-violation
spec:
  enforcementAction: deny
  match:
      kinds:
        - apiGroups: [""]
          kinds: ["HorizontalPodAutoscaler"]
  parameters:
    maxReplicas: 5
